# The file format version
version: '2'
# The services we want to create
services:
  # A DB service, using the redis image from the Docker repo
  db: redis
  # expose the default redis port
  ports:
    - "6379"
# A servie for web application
web:
  build: . # Run the build against the dockerfile in the current dir
  command: app.py # The CMD to be run
  volumes:
    - .app:/app # Folder mapping
  ports:
    - "5000:5000" # Port mapping
  depends_on:
    - db # Ensures the DB service is running
